<?php

namespace AgentReady\Features;

defined( 'ABSPATH' ) || exit;

/**
 * Serves a virtual /llms.txt file.
 */
class LLMS {

	public function init(): void {
		add_action( 'init', [ $this, 'add_rewrite_rule' ] );
		add_filter( 'query_vars', [ $this, 'add_query_var' ] );
		add_action( 'template_redirect', [ $this, 'serve' ] );
	}

	public function add_rewrite_rule(): void {
		add_rewrite_rule( '^llms\.txt$', 'index.php?agent_ready_llms_txt=1', 'top' );
	}

	public function add_query_var( array $vars ): array {
		$vars[] = 'agent_ready_llms_txt';
		return $vars;
	}

	public function serve(): void {
		if ( ! get_query_var( 'agent_ready_llms_txt' ) ) {
			return;
		}

		if ( ! (bool) get_option( 'agent_ready_enable_llms_txt', false ) ) {
			status_header( 404 );
			exit;
		}

		header( 'Content-Type: text/plain; charset=UTF-8' );
		header( 'Cache-Control: public, max-age=3600' );
		echo $this->get_content(); // phpcs:ignore WordPress.Security.EscapeOutput
		exit;
	}

	public function get_content(): string {
		$custom = (string) get_option( 'agent_ready_llms_txt_content', '' );
		return ! empty( trim( $custom ) ) ? $custom : $this->generate();
	}

	public function generate(): string {
		$name       = get_bloginfo( 'name' );
		$desc       = get_bloginfo( 'description' );
		$home       = home_url();
		$email      = get_bloginfo( 'admin_email' );
		$lang       = get_bloginfo( 'language' );

		$lines   = [];
		$lines[] = "# {$name}";
		$lines[] = '';

		if ( $desc ) {
			$lines[] = "> {$desc}";
			$lines[] = '';
		}

		$lines[] = '## Site Information';
		$lines[] = "- **URL**: {$home}";
		$lines[] = "- **Language**: {$lang}";
		$lines[] = "- **Contact**: {$email}";
		$lines[] = '';

		$lines[] = '## Key Pages';
		foreach ( get_pages( [ 'post_status' => 'publish', 'number' => 10 ] ) as $page ) {
			$lines[] = '- [' . esc_attr( get_the_title( $page ) ) . '](' . get_permalink( $page ) . ')';
		}
		$lines[] = '';

		$posts = get_posts( [ 'post_type' => 'post', 'posts_per_page' => 5, 'post_status' => 'publish' ] );
		if ( $posts ) {
			$lines[] = '## Recent Content';
			foreach ( $posts as $post ) {
				$lines[] = '- [' . esc_attr( get_the_title( $post ) ) . '](' . get_permalink( $post ) . ')';
			}
			$lines[] = '';
		}

		$caps = (array) get_option( 'agent_ready_capabilities_list', [] );
		if ( $caps ) {
			$lines[] = '## Capabilities';
			foreach ( $caps as $cap ) {
				$lines[] = '- ' . sanitize_text_field( $cap );
			}
			$lines[] = '';
		}

		$lines[] = '## AI Agent Endpoints';
		$lines[] = "- Summary: {$home}/wp-json/agent-ready/v1/summary";
		$lines[] = "- Content: {$home}/wp-json/agent-ready/v1/content";
		$lines[] = "- Capabilities: {$home}/wp-json/agent-ready/v1/capabilities";
		$lines[] = "- MCP Card: {$home}/.well-known/mcp";
		$lines[] = "- API Catalog: {$home}/.well-known/api-catalog";
		$lines[] = '';
		$lines[] = '---';
		$lines[] = "Generated by Agent Ready WordPress Plugin";

		return implode( "\n", $lines );
	}
}
